-   name: "freenode"
    server: "irc.freenode.net"
    port: 6667
    nickname: "SMAdventure"
    realname: "Sentient Mushes: Adventure"
    channels:
        - "#jongtest"
        - "#SMAdventure"

-   name: "mibbit"
    server: "irc.mibbit.net"
    port: 6667
    nickname: "SMAdventure"
    realname: "Sentient Mushes: Adventure"
    channels:
        - "#sentientmushes"
