-   name: "freenode"
    server: "irc.freenode.net"
    port: 6667
    nickname: "SMAdventure"
    channels:
        - "#jongtest"
        - "##lazy-valoran"
        
-   name: "mibbit"
    server: "irc.mibbit.net"
    port: 6667
    nickname: "SMAdventure"
    channels:
        - "#sentientmushes"